// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkhnnzqwigqvlmyxaqpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJraG5uenF3aWdxdmxteXhhcXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDE0OTcsImV4cCI6MjA3NzA3NzQ5N30.xZ_JZzuYfneLDaag1MMtYukawFW9T1ybY2wDQ6yPJkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});